#!/bin/bash
# =============================================================================
# FILE        : email_send.sh
# DESCRIPTION : Sends audit reports via email using msmtp or mail command
# AUTHOR      : Fettaka Sidahmed
# DATE        : 2026
# =============================================================================
# SETUP REQUIRED:
#   Option A (msmtp): Install msmtp and configure /etc/msmtprc or ~/.msmtprc
#   Option B (mail) : Install mailutils and configure postfix or sendmail
#
#   For Gmail with msmtp, create ~/.msmtprc with:
#     account default
#     host smtp.gmail.com
#     port 587
#     auth on
#     tls on
#     tls_starttls on
#     user your_email@gmail.com
#     password your_app_password   <- Use an App Password (not your real password!)
#     from your_email@gmail.com
#
#   IMPORTANT: Never put your real password in a config file.
#   Use Gmail App Passwords: https://myaccount.google.com/apppasswords
# =============================================================================

# =============================================================================
# FUNCTION: configure_msmtp
# PURPOSE : Write the msmtp config file if it doesn't exist
#           (This uses values from config.sh)
# =============================================================================
configure_msmtp() {
    local msmtp_config="$HOME/.msmtprc"

    if [ -f "$msmtp_config" ]; then
        log_message "INFO" "msmtp config already exists at $msmtp_config"
        return 0
    fi

    # Create the msmtp configuration file
    cat > "$msmtp_config" <<MSMTP_CONFIG
# msmtp configuration file
# Generated by NSCS Audit System

account default
host $SMTP_HOST
port $SMTP_PORT
auth on
tls on
tls_starttls on
user $SMTP_USER
password $SMTP_PASS
from $SMTP_USER
logfile $LOG_DIR/msmtp.log
MSMTP_CONFIG

    # Set permissions: only the owner can read it (protects the password)
    chmod 600 "$msmtp_config"
    log_message "INFO" "msmtp config written to $msmtp_config"
    echo -e "${GREEN}msmtp config created at $msmtp_config${NC}"
    echo -e "${YELLOW}IMPORTANT: Edit $msmtp_config and set your real email credentials.${NC}"
}

# =============================================================================
# FUNCTION: send_with_msmtp
# PURPOSE : Send an email using msmtp (recommended method)
# ARGS    : $1 = recipient, $2 = subject, $3 = body text, $4 = attachment (optional)
# =============================================================================
send_with_msmtp() {
    local recipient="$1"
    local subject="$2"
    local body="$3"
    local attachment="${4:-}"   # Optional file attachment

    # Check that msmtp is installed
    if ! check_command "msmtp"; then
        log_message "ERROR" "msmtp not installed. Run: sudo apt install msmtp"
        return 1
    fi

    # Build email content in RFC 2822 format
    # If there's an attachment, we do a simple base64 MIME email
    if [ -n "$attachment" ] && [ -f "$attachment" ]; then
        local filename
        filename=$(basename "$attachment")
        local boundary="----AuditBoundary$(date +%s)"

        {
            echo "To: $recipient"
            echo "Subject: $subject"
            echo "MIME-Version: 1.0"
            echo "Content-Type: multipart/mixed; boundary=\"$boundary\""
            echo ""
            echo "--$boundary"
            echo "Content-Type: text/plain; charset=UTF-8"
            echo ""
            echo "$body"
            echo ""
            echo "--$boundary"
            echo "Content-Type: text/plain; name=\"$filename\""
            echo "Content-Disposition: attachment; filename=\"$filename\""
            echo ""
            cat "$attachment"
            echo ""
            echo "--${boundary}--"
        } | msmtp "$recipient"

    else
        # Simple text email without attachment
        {
            echo "To: $recipient"
            echo "Subject: $subject"
            echo "Content-Type: text/plain; charset=UTF-8"
            echo ""
            echo "$body"
        } | msmtp "$recipient"
    fi

    return $?
}

# =============================================================================
# FUNCTION: send_with_mail
# PURPOSE : Send email using the 'mail' command (simpler fallback)
# ARGS    : $1 = recipient, $2 = subject, $3 = body, $4 = attachment (optional)
# =============================================================================
send_with_mail() {
    local recipient="$1"
    local subject="$2"
    local body="$3"
    local attachment="${4:-}"

    if ! check_command "mail"; then
        log_message "ERROR" "mail not installed. Run: sudo apt install mailutils"
        return 1
    fi

    if [ -n "$attachment" ] && [ -f "$attachment" ]; then
        echo "$body" | mail -s "$subject" -A "$attachment" "$recipient"
    else
        echo "$body" | mail -s "$subject" "$recipient"
    fi

    return $?
}

# =============================================================================
# FUNCTION: send_report_email
# PURPOSE : Interactive function to send a report via email
#           Tries msmtp first, falls back to mail command
# =============================================================================
send_report_email() {
    section_header "Email Report Transmission"

    # Ask the user what type of report to send
    echo "Which report type do you want to send?"
    echo "  1) Short Report"
    echo "  2) Full Report"
    echo -n "Choice (1 or 2): "
    read -r type_choice

    local report_type
    case "$type_choice" in
        1) report_type="short" ;;
        2) report_type="full" ;;
        *)
            echo -e "${RED}Invalid choice.${NC}"
            return 1
            ;;
    esac

    # Run the audit if reports don't exist yet
    if [ -z "$LAST_REPORT_TXT" ]; then
        log_message "INFO" "No report generated yet. Running audit first..."
        collect_hardware_info
        collect_software_info
        generate_report "$report_type"
    fi

    # Ask for recipient email (default from config)
    echo -n "Send to email [$EMAIL_RECIPIENT]: "
    read -r recipient_input
    local recipient="${recipient_input:-$EMAIL_RECIPIENT}"

    # Validate email format (basic check: must contain @)
    if ! echo "$recipient" | grep -q "@"; then
        log_message "ERROR" "Invalid email address: $recipient"
        echo -e "${RED}Invalid email address.${NC}"
        return 1
    fi

    local subject="$EMAIL_SUBJECT"
    local body="Hello,

This is your automated system audit report from: $HOSTNAME_VAL
Date: $(get_date_readable)
Report Type: ${report_type^^}

Please find the attached report file.

-- NSCS Audit System"

    log_message "INFO" "Sending $report_type report to $recipient..."
    echo -e "${YELLOW}Sending email to $recipient...${NC}"

    # Try msmtp first, then fall back to mail command
    if check_command "msmtp"; then
        configure_msmtp
        send_with_msmtp "$recipient" "$subject" "$body" "$LAST_REPORT_TXT"
    elif check_command "mail"; then
        send_with_mail "$recipient" "$subject" "$body" "$LAST_REPORT_TXT"
    elif check_command "sendmail"; then
        echo "$body" | sendmail -v "$recipient"
    else
        log_message "ERROR" "No email client found. Install msmtp: sudo apt install msmtp"
        echo -e "${RED}No email client found.${NC}"
        echo "Install msmtp with: sudo apt install msmtp"
        return 1
    fi

    # Check if the send command succeeded (exit code 0 = success)
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}Email sent successfully to: $recipient${NC}"
        log_message "INFO" "Email sent to $recipient"
    else
        echo -e "${RED}Failed to send email. Check your SMTP configuration in config.sh${NC}"
        log_message "ERROR" "Failed to send email to $recipient"
        return 1
    fi
}
