#!/bin/bash
# =============================================================================
# FILE        : report.sh
# DESCRIPTION : Generates formatted audit reports (short & full) in multiple formats
# AUTHOR      : Fettaka Sidahmed
# DATE        : 2026
# =============================================================================
# Generates: .txt, .html, and .json reports
# Saves to: $REPORT_DIR
# =============================================================================

# Will hold the path to the last generated report (used by email module)
LAST_REPORT_TXT=""
LAST_REPORT_HTML=""
LAST_REPORT_JSON=""

# =============================================================================
# FUNCTION: build_txt_report
# PURPOSE : Write the report content as plain text to a file
# ARGS    : $1 = output file path, $2 = report type ("short" or "full")
# =============================================================================
build_txt_report() {
    local outfile="$1"
    local report_type="$2"
    local date_str
    date_str=$(get_date_readable)
    local sep="============================================================"
    local thin_sep="------------------------------------------------------------"

    {
        # ---- Report Header ----
        echo "$sep"
        echo "  LINUX SYSTEM AUDIT REPORT"
        echo "  Type     : $(echo "$report_type" | tr '[:lower:]' '[:upper:]') REPORT"
        echo "  Hostname : $HOSTNAME_VAL"
        echo "  Date     : $date_str"
        echo "  Generated by: NSCS Audit System"
        echo "$sep"
        echo ""

        # ========== HARDWARE SECTION ==========
        echo "$sep"
        echo "  SECTION 1 : HARDWARE INFORMATION"
        echo "$sep"
        echo ""

        echo "[ CPU ]"
        echo "$thin_sep"
        echo "  Model        : ${HW_CPU:-N/A}"
        echo "  Cores        : ${HW_CPU_CORES:-N/A}"
        echo "  Architecture : ${HW_CPU_ARCH:-N/A}"
        echo ""

        echo "[ GPU ]"
        echo "$thin_sep"
        echo "  ${HW_GPU:-N/A}"
        echo ""

        echo "[ MEMORY (RAM) ]"
        echo "$thin_sep"
        echo "  Total     : ${HW_RAM_TOTAL:-N/A} MB"
        echo "  Used      : ${HW_RAM_USED:-N/A} MB"
        echo "  Available : ${HW_RAM_FREE:-N/A} MB"
        echo ""

        echo "[ DISK / STORAGE ]"
        echo "$thin_sep"
        if [ "$report_type" = "full" ]; then
            echo "  Block Devices:"
            echo "${HW_PARTITIONS:-N/A}" | sed 's/^/    /'
            echo ""
            echo "  Disk Usage:"
            echo "${HW_DISK:-N/A}" | sed 's/^/    /'
        else
            # Short report: just show disk usage summary
            echo "${HW_DISK:-N/A}" | sed 's/^/  /'
        fi
        echo ""

        echo "[ NETWORK INTERFACES ]"
        echo "$thin_sep"
        echo "${HW_NETWORK:-N/A}" | sed 's/^/  /'
        echo ""

        if [ "$report_type" = "full" ]; then
            echo "[ MAC & IP ADDRESSES ]"
            echo "$thin_sep"
            echo "${HW_MAC_IP:-N/A}" | sed 's/^/  /'
            echo ""
        fi

        echo "[ MOTHERBOARD ]"
        echo "$thin_sep"
        echo "  ${HW_MOTHERBOARD:-N/A}"
        echo ""

        if [ "$report_type" = "full" ]; then
            echo "[ USB DEVICES ]"
            echo "$thin_sep"
            echo "${HW_USB:-N/A}" | sed 's/^/  /'
            echo ""
        fi

        # ========== SOFTWARE SECTION ==========
        echo "$sep"
        echo "  SECTION 2 : OPERATING SYSTEM & SOFTWARE INFORMATION"
        echo "$sep"
        echo ""

        echo "[ OPERATING SYSTEM ]"
        echo "$thin_sep"
        echo "  OS Name      : ${SW_OS_NAME:-N/A}"
        echo "  OS Version   : ${SW_OS_VERSION:-N/A}"
        echo "  Kernel       : ${SW_KERNEL:-N/A}"
        echo "  Architecture : ${SW_ARCH:-N/A}"
        echo "  Uptime       : ${SW_UPTIME:-N/A}"
        echo "  Shell        : ${SW_SHELL:-N/A}"
        echo ""

        echo "[ INSTALLED PACKAGES ]"
        echo "$thin_sep"
        echo "  Total installed: ${SW_PACKAGE_COUNT:-N/A}"
        if [ "$report_type" = "full" ]; then
            echo ""
            echo "  Package list:"
            # Show all packages (can be long in full report)
            echo "${SW_PACKAGES:-N/A}" | sed 's/^/    /'
        else
            # Short report: show only first 20 packages
            echo ""
            echo "  First 20 packages:"
            echo "${SW_PACKAGES:-N/A}" | head -20 | sed 's/^/    /'
            echo "    ... (use full report to see all)"
        fi
        echo ""

        echo "[ LOGGED-IN USERS ]"
        echo "$thin_sep"
        echo "${SW_LOGGED_USERS:-N/A}" | sed 's/^/  /'
        echo ""

        echo "[ OPEN PORTS ]"
        echo "$thin_sep"
        echo "${SW_OPEN_PORTS:-N/A}" | sed 's/^/  /'
        echo ""

        if [ "$report_type" = "full" ]; then
            echo "[ RUNNING SERVICES ]"
            echo "$thin_sep"
            echo "${SW_SERVICES:-N/A}" | sed 's/^/  /'
            echo ""

            echo "[ TOP ACTIVE PROCESSES (by CPU) ]"
            echo "$thin_sep"
            echo "${SW_PROCESSES:-N/A}" | sed 's/^/  /'
            echo ""
        fi

        # ---- Footer ----
        echo "$sep"
        echo "  END OF REPORT"
        echo "$sep"
        echo ""

    } > "$outfile"
}

# =============================================================================
# FUNCTION: build_html_report
# PURPOSE : Write the report as a styled HTML file
# ARGS    : $1 = output file path, $2 = report type
# =============================================================================
build_html_report() {
    local outfile="$1"
    local report_type="$2"
    local date_str
    date_str=$(get_date_readable)

    {
        cat <<HTML_HEADER
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Audit Report - $HOSTNAME_VAL</title>
    <style>
        body { font-family: monospace; background: #1e1e2e; color: #cdd6f4; margin: 20px; }
        h1 { color: #89b4fa; border-bottom: 2px solid #89b4fa; }
        h2 { color: #a6e3a1; margin-top: 30px; }
        h3 { color: #f38ba8; }
        .info-table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        .info-table td { padding: 5px 10px; border: 1px solid #45475a; }
        .info-table td:first-child { color: #fab387; font-weight: bold; width: 200px; }
        pre { background: #181825; padding: 10px; border-radius: 5px; overflow-x: auto;
              color: #cdd6f4; font-size: 13px; }
        .footer { margin-top: 40px; color: #6c7086; font-size: 12px; text-align: center; }
        .badge { display:inline-block; padding:2px 8px; border-radius:4px;
                 background:#89dceb; color:#1e1e2e; font-weight:bold; }
    </style>
</head>
<body>
<h1>&#128196; Linux System Audit Report</h1>
<table class="info-table">
  <tr><td>Report Type</td><td><span class="badge">$(echo "$report_type" | tr '[:lower:]' '[:upper:]')</span></td></tr>
  <tr><td>Hostname</td><td>$HOSTNAME_VAL</td></tr>
  <tr><td>Date &amp; Time</td><td>$date_str</td></tr>
  <tr><td>Generated by</td><td>NSCS Audit System</td></tr>
</table>

<h2>&#128187; Section 1: Hardware Information</h2>

<h3>CPU</h3>
<table class="info-table">
  <tr><td>Model</td><td>${HW_CPU:-N/A}</td></tr>
  <tr><td>Cores</td><td>${HW_CPU_CORES:-N/A}</td></tr>
  <tr><td>Architecture</td><td>${HW_CPU_ARCH:-N/A}</td></tr>
</table>

<h3>GPU</h3>
<pre>${HW_GPU:-N/A}</pre>

<h3>RAM (Memory)</h3>
<table class="info-table">
  <tr><td>Total</td><td>${HW_RAM_TOTAL:-N/A} MB</td></tr>
  <tr><td>Used</td><td>${HW_RAM_USED:-N/A} MB</td></tr>
  <tr><td>Available</td><td>${HW_RAM_FREE:-N/A} MB</td></tr>
</table>

<h3>Disk / Storage</h3>
<pre>${HW_DISK:-N/A}</pre>
HTML_HEADER

        if [ "$report_type" = "full" ]; then
            echo "<h3>Disk Partitions (lsblk)</h3>"
            echo "<pre>${HW_PARTITIONS:-N/A}</pre>"
        fi

        cat <<HTML_NET
<h3>Network Interfaces</h3>
<pre>${HW_NETWORK:-N/A}</pre>
HTML_NET

        if [ "$report_type" = "full" ]; then
            echo "<h3>MAC &amp; IP Addresses</h3>"
            echo "<pre>${HW_MAC_IP:-N/A}</pre>"
            echo "<h3>USB Devices</h3>"
            echo "<pre>${HW_USB:-N/A}</pre>"
        fi

        cat <<HTML_SW
<h3>Motherboard</h3>
<pre>${HW_MOTHERBOARD:-N/A}</pre>

<h2>&#128196; Section 2: OS &amp; Software Information</h2>

<h3>Operating System</h3>
<table class="info-table">
  <tr><td>OS Name</td><td>${SW_OS_NAME:-N/A}</td></tr>
  <tr><td>OS Version</td><td>${SW_OS_VERSION:-N/A}</td></tr>
  <tr><td>Kernel</td><td>${SW_KERNEL:-N/A}</td></tr>
  <tr><td>Architecture</td><td>${SW_ARCH:-N/A}</td></tr>
  <tr><td>Uptime</td><td>${SW_UPTIME:-N/A}</td></tr>
  <tr><td>Shell</td><td>${SW_SHELL:-N/A}</td></tr>
</table>

<h3>Installed Packages</h3>
<p>Total installed: <strong>${SW_PACKAGE_COUNT:-N/A}</strong></p>
HTML_SW

        if [ "$report_type" = "full" ]; then
            echo "<pre>${SW_PACKAGES:-N/A}</pre>"
        else
            echo "<pre>$(echo "${SW_PACKAGES:-N/A}" | head -20)
... (use full report to see all)</pre>"
        fi

        cat <<HTML_FOOT
<h3>Logged-in Users</h3>
<pre>${SW_LOGGED_USERS:-N/A}</pre>

<h3>Open Ports</h3>
<pre>${SW_OPEN_PORTS:-N/A}</pre>
HTML_FOOT

        if [ "$report_type" = "full" ]; then
            echo "<h3>Running Services</h3>"
            echo "<pre>${SW_SERVICES:-N/A}</pre>"
            echo "<h3>Active Processes (Top by CPU)</h3>"
            echo "<pre>${SW_PROCESSES:-N/A}</pre>"
        fi

        echo "<div class='footer'>Generated by NSCS Audit System &mdash; $date_str</div>"
        echo "</body></html>"

    } > "$outfile"
}

# =============================================================================
# FUNCTION: build_json_report
# PURPOSE : Write the report in JSON format for machine readability
# ARGS    : $1 = output file path, $2 = report type
# =============================================================================
build_json_report() {
    local outfile="$1"
    local report_type="$2"
    local timestamp
    timestamp=$(date '+%Y-%m-%dT%H:%M:%S')

    # We use printf with escaped values to build valid JSON
    # Note: this is a simplified JSON builder - for production you'd use jq
    {
        printf '{\n'
        printf '  "report_metadata": {\n'
        printf '    "type": "%s",\n' "$report_type"
        printf '    "hostname": "%s",\n' "$HOSTNAME_VAL"
        printf '    "timestamp": "%s",\n' "$timestamp"
        printf '    "generator": "NSCS Audit System"\n'
        printf '  },\n'
        printf '  "hardware": {\n'
        printf '    "cpu_model": "%s",\n' "$(echo "$HW_CPU" | sed 's/"/\\"/g')"
        printf '    "cpu_cores": "%s",\n' "$HW_CPU_CORES"
        printf '    "cpu_arch": "%s",\n' "$HW_CPU_ARCH"
        printf '    "gpu": "%s",\n' "$(echo "$HW_GPU" | head -1 | sed 's/"/\\"/g')"
        printf '    "ram_total_mb": "%s",\n' "$HW_RAM_TOTAL"
        printf '    "ram_used_mb": "%s",\n' "$HW_RAM_USED"
        printf '    "ram_free_mb": "%s",\n' "$HW_RAM_FREE"
        printf '    "motherboard": "%s"\n' "$(echo "$HW_MOTHERBOARD" | sed 's/"/\\"/g')"
        printf '  },\n'
        printf '  "software": {\n'
        printf '    "os_name": "%s",\n' "$SW_OS_NAME"
        printf '    "os_version": "%s",\n' "$SW_OS_VERSION"
        printf '    "kernel": "%s",\n' "$SW_KERNEL"
        printf '    "arch": "%s",\n' "$SW_ARCH"
        printf '    "uptime": "%s",\n' "$(echo "$SW_UPTIME" | sed 's/"/\\"/g')"
        printf '    "shell": "%s",\n' "$SW_SHELL"
        printf '    "package_count": "%s"\n' "$SW_PACKAGE_COUNT"
        printf '  }\n'
        printf '}\n'
    } > "$outfile"
}

# =============================================================================
# FUNCTION: generate_report
# PURPOSE : Orchestrate report generation in all formats (txt, html, json)
# ARGS    : $1 = report type ("short" or "full")
# =============================================================================
generate_report() {
    local report_type="${1:-short}"
    local timestamp
    timestamp=$(get_timestamp)

    # Make sure the report directory exists
    mkdir -p "$REPORT_DIR"

    # Build file names using hostname + timestamp + type
    local base_name="${HOSTNAME_VAL}_${report_type}_${timestamp}"
    local txt_file="$REPORT_DIR/${base_name}.txt"
    local html_file="$REPORT_DIR/${base_name}.html"
    local json_file="$REPORT_DIR/${base_name}.json"

    section_header "Generating ${report_type^^} Report"

    # --- Generate TXT ---
    echo -e "${YELLOW}Creating TXT report...${NC}"
    build_txt_report "$txt_file" "$report_type"
    if [ -f "$txt_file" ]; then
        echo -e "${GREEN}  ✓ TXT  → $txt_file${NC}"
        LAST_REPORT_TXT="$txt_file"
        # Create a SHA256 hash for integrity checking
        verify_log_integrity "$txt_file" "create"
    fi

    # --- Generate HTML ---
    echo -e "${YELLOW}Creating HTML report...${NC}"
    build_html_report "$html_file" "$report_type"
    if [ -f "$html_file" ]; then
        echo -e "${GREEN}  ✓ HTML → $html_file${NC}"
        LAST_REPORT_HTML="$html_file"
    fi

    # --- Generate JSON ---
    echo -e "${YELLOW}Creating JSON report...${NC}"
    build_json_report "$json_file" "$report_type"
    if [ -f "$json_file" ]; then
        echo -e "${GREEN}  ✓ JSON → $json_file${NC}"
        LAST_REPORT_JSON="$json_file"
    fi

    echo ""
    echo -e "${GREEN}All reports saved to: $REPORT_DIR${NC}"
    log_message "INFO" "Reports generated: $base_name (.txt, .html, .json)"

    # Rotate old reports: keep only the last 20
    rotate_logs "$REPORT_DIR" 20
}
